version: "3.8"
services:
  firefox:
    image: selenium/standalone-firefox:latest
    hostname: firefox
    privileged: true
#    shm-size: 2g
    ports:
      - "4441:4444"
      - "7901:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
#    shm_size: 2g
    ports:
      - "4442:4444"
      - "7902:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1

